#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake -j libso um_particle
wmake -j libso biomassParticle
wmake -j libso radiation
wmake -j
#------------------------------------------------------------------------------
