#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso um_particle
wclean libso biomassParticle
wclean libso radiation
wclean setParticles
wclean setParticlesSeparation
wclean PBMFoam

#------------------------------------------------------------------------------
