#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake -j libso vegetationBed
wmake -j libso radiation
wmake -j
#------------------------------------------------------------------------------
