UMParticle: main.cpp \
			air.h air.cpp \
			fluid.h fluid.cpp \
			solidMaterial.h solidMaterial.cpp \
			particle.h particle.cpp \
			particle_1D.h particle_1D.cpp \
			solidReaction.h solidReaction.cpp \
			TDMA.h TDMA.cpp \
			particleShape.h particleShape.cpp \
			cylinder.h cylinder.cpp\
			slab.h slab.cpp \
			sphere.h sphere.cpp

	g++ 	main.cpp \
			air.cpp \
			fluid.cpp \
			solidMaterial.cpp \
			particle.cpp \
			particle_1D.cpp \
			solidReaction.cpp \
			TDMA.cpp \
			particleShape.cpp \
			cylinder.cpp \
			slab.cpp \
			sphere.cpp \
			-lgomp -o UMParticle
			
clean:

	rm UMParticle
